# reports/report_generator.py

import os
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

# Output folder
OUTPUT_DIR = "reports/generated_pdfs"

# Create folder if it doesn't exist
os.makedirs(OUTPUT_DIR, exist_ok=True)


def generate_student_report(student_id, accuracy, weak_topics):
    """
    Generate PDF report for a student.

    Parameters:
    student_id : str
    accuracy : float
    weak_topics : list
    """

    filename = os.path.join(
        OUTPUT_DIR,
        f"student_report_{student_id}.pdf"
    )

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    # -------------------------
    # Title
    # -------------------------
    title = Paragraph(
        f"<b>Student Performance Report</b>",
        styles["Title"]
    )

    elements.append(title)
    elements.append(Spacer(1, 20))

    # -------------------------
    # Student Details
    # -------------------------
    student_info = [
        ["Student ID", str(student_id)],
        ["Accuracy", f"{accuracy:.2f}%"]
    ]

    info_table = Table(student_info, colWidths=[150, 250])

    info_table.setStyle(
        TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold')
        ])
    )

    elements.append(info_table)
    elements.append(Spacer(1, 20))

    # -------------------------
    # Performance Summary
    # -------------------------
    elements.append(
        Paragraph(
            "<b>Performance Summary</b>",
            styles["Heading2"]
        )
    )

    if accuracy >= 80:
        performance_text = (
            "Excellent performance. "
            "The student demonstrates strong understanding "
            "of most concepts."
        )
    elif accuracy >= 60:
        performance_text = (
            "Good performance. "
            "There is scope for improvement in certain topics."
        )
    else:
        performance_text = (
            "Needs improvement. "
            "Additional practice and revision are recommended."
        )

    elements.append(
        Paragraph(performance_text, styles["BodyText"])
    )

    elements.append(Spacer(1, 20))

    # -------------------------
    # Weak Topics Section
    # -------------------------
    elements.append(
        Paragraph(
            "<b>Weak Topics Identified</b>",
            styles["Heading2"]
        )
    )

    if weak_topics:

        topic_data = [["Topic"]]

        for topic in weak_topics:
            topic_data.append([topic])

        topic_table = Table(topic_data, colWidths=[300])

        topic_table.setStyle(
            TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.red),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica')
            ])
        )

        elements.append(topic_table)

    else:
        elements.append(
            Paragraph(
                "No weak topics identified.",
                styles["BodyText"]
            )
        )

    elements.append(Spacer(1, 20))

    # -------------------------
    # Recommendations
    # -------------------------
    elements.append(
        Paragraph(
            "<b>Recommendations</b>",
            styles["Heading2"]
        )
    )

    recommendations = [
        "Revise weak topics regularly.",
        "Attempt topic-wise mock tests.",
        "Analyze mistakes after every assessment.",
        "Maintain a revision schedule.",
        "Focus on conceptual understanding."
    ]

    for rec in recommendations:
        elements.append(
            Paragraph(f"• {rec}", styles["BodyText"])
        )

    elements.append(Spacer(1, 20))

    # -------------------------
    # Footer
    # -------------------------
    elements.append(
        Paragraph(
            "Generated by Automated Mock Test Insights Engine",
            styles["Italic"]
        )
    )

    doc.build(elements)

    print(f"PDF generated: {filename}")

    return filename


# -------------------------------------------------
# Sample Test
# -------------------------------------------------
if __name__ == "__main__":

    generate_student_report(
        student_id="STU001",
        accuracy=78.45,
        weak_topics=[
            "Data Structures",
            "DBMS",
            "Operating Systems"
        ]
    )
